### PR TITLE
updated basics section

### PR DESCRIPTION
**Pull request by everly-gif**
**Solved issue #115**  

Your First PR has become an archived repository, meaning it's now read-only. Therefore, I have removed it from the basics section of the home page (index.html)  .

### CODE REVIEW

**Review by ramyaparimi — APPROVED** [review]
@everly-gif Thanks so much for working on the issue and creating this PR 🚀  I will go ahead and merge this change ✨

**Comment by everly-gif** [comment]
@ramyaparimi is there anything I should do to resolve the conflict?

**Comment by ramyaparimi** [comment]
@everly-gif probably not at the moment! I will get back to you once I have an update ⚡  Thank you 👍

**Comment by jwflory** [comment]
Apologies on the delay in reviewing this. I am inching forward on the backlog here. This was fixed in PR #132. Thanks @everly-gif for making the contribution anyways. Feel free to join us either [on Telegram](https://t.me/diversityandinclusioninoss) or [on Signal](https://signal.group/#CjQKIBCrnNZU2ROCBP5ysJgdiYJBPNxIKT3tkktcMTywdgOUEhBbZbRk0doCcoAGC6Vauv14) and share an introduction there.

**Pull request closed without merging**
