### PR TITLE
Add Hacktoberfest in Programs Section

### PR DESCRIPTION
**Pull request by dipu989**
Related Issue #52
 
Related Chat:-
https://github.com/opensourcediversity/opensourcediversity.org/issues/52#issuecomment-439722426

I have updated the PR as per the instruction and have tested it locally too!
@jancborchardt

### CODE REVIEW

**Comment by jancborchardt** [comment]
@dipu989 good stuff! The commit 3d8da5b  with the slide modification seems to be an error though, can you make sure you are basing it on current master? :)

**Comment by dipu989** [comment]
@jancborchardt 
Ah Yes, This seems to be an extra commit in the PR.
I followed this guideline to create the PR:-
1)  git fetch --all (in branch master)
 2) git checkout -b new-branch-name upstream/master
3)git cherry-pick *commit*
4)  git push -u origin new-branch-name
 Then I Opened PR from my forked repo.
Any Idea what might be wrong?
Thank You!

**Comment by jancborchardt** [comment]
@dipu989 let’s see – what I normally do is similar to your commands but a bit different:

1. Be on master, do a `git pull original master` (not sure if git fetch is enough, and "original" is probably called "upstream" for you?)
2. `git checkout -b new-branch-name`
3. `git cherry-pick commit`
4. `git push origin new-branch-name` (where "origin" is your fork of the repo)

Could you try that out and let me know how it works? Sorry about the breakage!

**Comment by jancborchardt** [comment]
@dipu989 maybe it’s best to just start off again with master, do a fresh branch, and just manually do the changes again? Sorry for the hassle. :\

**Comment by dipu989** [comment]
Closing this PR to avoid any confusion!

**Pull request closed without merging**
