### PR TITLE
Twitter feed and follow button

### PR DESCRIPTION
**Pull request by colbye9**
Hope this can be useful to you. Ignore the first commit with changes to the scripts at the bottom. I fixed that in the second.

### CODE REVIEW

**Comment by jancborchardt** [comment]
There is already an active pull request doing this at #8 :) See the screenshot at https://github.com/opensourcediversity/opensourcediversity.org/pull/8#issuecomment-393253663

Maybe it’s best if we continue there? It would be awesome if you can test that one!

**Comment by Roshanjossey** [comment]
@jancborchardt, I wan't aware of that. I'll continue on the conversation here.

**Comment by jancborchardt** [comment]
@Roshanjossey @colbye9 yeah, sorry for the confusion! :) The #8 is also almost done, just needs finishing touches and testing. Should we close this pull request here then to continue at #8?

**Comment by jancborchardt** [comment]
The pull request for Twitter and Meetup integration is now updated at https://github.com/opensourcediversity/opensourcediversity.org/pull/73 :)

I also added the helpful data-chrome attributes from here to there via https://github.com/opensourcediversity/opensourcediversity.org/pull/73/commits/0140aa2dc40c437a475ad9c58c7ca1896844223a – thanks a lot @colbye9 @Roshanjossey! There’s a bunch more issues to check out at https://github.com/opensourcediversity/opensourcediversity.org/issues and more pull requests to review at https://github.com/opensourcediversity/opensourcediversity.org/pulls

**Pull request closed without merging**
