### PR TITLE
Add CHAOSS project

### PR DESCRIPTION
**Pull request by GeorgLink**
The CHAOSS D&I workgroup is collecting resources for projects to create a diversity and inclusion report. 

Proposing this pull request as an outcome of the presentation during Emma Irwin's call today.

Please let me know if you need more information.

Thank you!

### CODE REVIEW

**Comment by dmgerman** [comment]
One suggestion. the description of the pull request is not very informative (nor the first commit summary). Aside from explaining why the pull request is done, it is useful tosummarize the changes. In this case, it seems that is only to add a link to CHAOSS and its logo.

**Comment by GeorgLink** [comment]
Thanks @dmgerman 

Yes, this pull request adds CHAOSS under projects including an image.

**Comment by jonatoni** [comment]
@GeorgLink thank you for adding CHAOSS :)

**Comment by GeorgLink** [comment]
Thank you!

**Comment by jancborchardt** [comment]
Thank you @GeorgLink for adding it. :) Do feel free to propose other projects too.

**Comment by GeorgLink** [comment]
@jancborchardt perfect timing to ask me. I was just looking at the Open Demographics project and promptly created a pull request #32

**Pull request merged**
