### PR TITLE
fixed contact logo in mobile UI

### LINKED ISSUE #20: Contact icon not appearing in mobile UI
### Actual result
Github, Twitter and IRC icons are not there in mobile UI.

### Expected result
It should be in menu where Events, Articles etc are too.

### PR DESCRIPTION
**Pull request by drashti4**
added logo of twitter, IRC and Github in mobile UI
Fixed #20

### CODE REVIEW

**Comment by jancborchardt** [comment]
@drashti4 looks good and fixes the issue! :) Could you just fix the whitespace, like extra added empty lines and spaces?
screenshot from 2018-06-11 17-39-08

Thanks!

**Comment by jancborchardt** [comment]
(And by the way, since you are member of this organization, you can also open branches of this repository directly, and you don’t need a personal fork. :) Then on small fixes like these whitespace things, we can directly collaborate on the branch.)

**Comment by drashti4** [comment]
Thank you for it. It is perfectly indented now.

**Comment by jancborchardt** [comment]
@drashti4 sorry, the whitespace was just all over the place afterwards, as visible in the changes tab at https://github.com/opensourcediversity/opensourcediversity.org/pull/21/files – did you do some automatic replacement?

I quickly reverted this change through https://github.com/opensourcediversity/opensourcediversity.org/pull/22 so it doesn’t interfere with the other already open pull requests.

Could you open a new pull request and only include the change which is used to fix #20 – namely removing the `d-none d-md-flex`. Thank you, and sorry for the issues. :)

**Comment by jancborchardt** [comment]
@drashti4 after an additional change it’s always good to wait for another review. :) There’s no rush in getting things done.

**Pull request merged**
