### PR TITLE
Additional photos

### PR DESCRIPTION
**Pull request by jancborchardt**
@Haimchen @sleepypioneer @alicetragedy do we have any pictures from the 2018-11 Code more event? Would be cool to add them here for possible promotion use and also for remembering. :)

### CODE REVIEW

**Comment by jancborchardt** [comment]
@Haimchen the photos from the contribution day in the tweet at https://twitter.com/osdiversity/status/1185600089441652736 were from your phone, right? The Twitter ones are a bit small/compressed I guess, could you add the originals here? :)

**Comment by Haimchen** [comment]
@jancborchardt I uploaded 3 of the photos from hacktoberfest from my phone. I have a few more, but they are all very similar, so I tried to pick the good ones :)

**Comment by jancborchardt** [comment]
@Haimchen really cool! :) Do you have some from the Code more event too by any chance?

**Comment by Haimchen** [comment]
@jancborchardt I looked through my phone, but it seems I have no pictures from that event :-(

**Comment by jancborchardt** [comment]
Then let’s first merge this one :)

**Pull request merged**
