### PR TITLE
add open demographics project, but missing image

### PR DESCRIPTION
**Pull request by GeorgLink**
I propose to add the Open Demographics project, but they do not seem to have an image.

### CODE REVIEW

**Comment by GeorgLink** [comment]
I asked the Open Demographics project whether they have a logo: drnikki/open-demographics#50

**Comment by jancborchardt** [comment]
It would be cool if there’s a logo, even if it’s just a screenshot of the text in the top right of the website. :)

@drnikki does the project have a logo by any chance? If not, feel free to submit a job to the [Open Source Design job board](https://opensourcedesign.net/jobs/)! :)

**Comment by GeorgLink** [comment]
Thanks @jancborchardt for the idea with the screenshot. I have added one.

**Comment by jancborchardt** [comment]
@GeorgLink sorry, I misspoke and meant the text on the top left, that is the logo only. :)
opendemographics
See [source file](https://cloud.jancborchardt.net/s/6FcW2fxCei6i5Lj) since I’m not sure if GitHub uploads get artifacts.

Could you replace the image in your pull request with that? :)

**Comment by GeorgLink** [comment]
Thanks for the file @jancborchardt 
The pull request is updated!

**Comment by jancborchardt** [comment]
Good stuff @GeorgLink, thanks a lot and welcome to the team! :tada: 

If you have any input on the possible "Consulting" category that would be appreciated too :) https://github.com/opensourcediversity/opensourcediversity.org/issues/31

**Comment by GeorgLink** [comment]
Thanks for the quick turnaround!

**Pull request merged**
