### PR TITLE
Adding few articles for people with disabilities

### PR DESCRIPTION
**Pull request by tapaswenipathak**
Ref https://github.com/opensourcediversity/opensourcediversity.org/issues/42. 

Hey folks: I added few articles as described in the ticket, lemme know if you have a collection would like me PRing.

### CODE REVIEW

**Comment by jancborchardt** [comment]
Good stuff! :) Some review:
- The link is the same all 3 times
- The first and second entry are the same?
- The link for the third article is: https://longmoreinstitute.sfsu.edu/there%E2%80%99s-always-something-be-done-liz-henry-being-disabled-tech, right?
- The first/second article is not specific to open source but tech in general, where there’s lots of content anyway. We want to focus on the intersection of open source and inclusion/diversity specifically, not only tech in general. :)

So I’d personally say let’s only add the article: https://longmoreinstitute.sfsu.edu/there%E2%80%99s-always-something-be-done-liz-henry-being-disabled-tech

What do you think? :)

**Comment by tapaswenipathak** [comment]
On Mon, Aug 26, 2019 at 9:42 PM Jan-Christoph Borchardt
<notifications@github.com> wrote:
>
> Good stuff! :) Some review:
>
> The link is the same all 3 times
> The first and second entry are the same?
> The link for the third article is: https://longmoreinstitute.sfsu.edu/there%E2%80%99s-always-something-be-done-liz-henry-being-disabled-tech, right?
> The first/second article is not specific to open source but tech in general, where there’s lots of content anyway. We want to focus on the intersection of open source and inclusion/diversity specifically, not only tech in general. :)
>
> So I’d personally say let’s only add the article: https://longmoreinstitute.sfsu.edu/there%E2%80%99s-always-something-be-done-liz-henry-being-disabled-tech
>
> What do you think? :)

I would add the WordPress blog as well. After you added the comments,
I just observed the PR little and I found sever issues in that. I will
be pushing a commit. :)
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.



-- 
Tapasweni

**Comment by jonatoni** [comment]
> So I’d personally say let’s only add the article: [longmoreinstitute.sfsu.edu/there%E2%80%99s-always-something-be-done-liz-henry-being-disabled-tech](https://longmoreinstitute.sfsu.edu/there%E2%80%99s-always-something-be-done-liz-henry-being-disabled-tech)

+1, I agree with @jancborchardt

**Comment by tapaswenipathak** [comment]
No probs! Done.

**Pull request merged**
