### PR TITLE
Service workers for progressive app

### PR DESCRIPTION
**Pull request by peeyushsingla**
[Google Sample repo](https://codelabs.developers.google.com/codelabs/offline/#0)

### CODE REVIEW

**Comment by jancborchardt** [comment]
@peeyushsingla good stuff! Would only adjust a few details:
- cache-polyfill.js could go in the vendor folder cause it's a set js "library"
- sw.js could go into a new "js" folder
- sw.js could be renamed to "serviceworker.js" so it's more obvious

What do you think? :) Will test later if it works, am mobile at the moment.

**Comment by peeyushsingla** [comment]
@jancborchardt I think yes suggestion are very relevant, would it be fine if I push changes over the weekend?

**Comment by peeyushsingla** [comment]
@jancborchardt I found there are some [errors](https://www.dropbox.com/s/b9q1b36mqstyovp/Screenshot%202018-07-29%2018.48.39.png?dl=0) in console on master?:-

**Comment by peeyushsingla** [comment]
@jancborchardt about moving the `service_worker` to `js` folder there is a security issue. 

```The location of the service worker is important! For security reasons, a service worker can only control the pages that are in its same directory or its subdirectories. This means that if you place the service worker file in a scripts directory it will only be able to interact with pages in the scripts directory or below.```

**Comment by jancborchardt** [comment]
@peeyushsingla cool, I wasn’t aware of the placement of the service worker file! :)

I’ll review the pull request now, sorry for the delay.

**Comment by jancborchardt** [comment]
@peeyushsingla did you find a good way to set up a local https server? I used https://stackoverflow.com/questions/19705785/python-3-https-webserver but can’t make it work :\ Without it I get `Only secure origins are allowed` and with it and self-signed cert I get `Failed to register a ServiceWorker: An SSL certificate error occurred when fetching the script.`


Also, is there a reason the versioning of the cache is left out? Maybe it’s a good idea to put that in so it will be updated when something changes? :) https://github.com/GoogleChromeLabs/airhorn/blob/master/app/sw.js#L20

**Comment by peeyushsingla** [comment]
@jancborchardt I am using this `python -m SimpleHTTPServer 8000` to run the http server, yes you are right it will require the files be server by http server.

**Comment by peeyushsingla** [comment]
@jancborchardt added caching but when I am testing even updating the cache version isn't updating the cached data, could you please have a look?

**Comment by jancborchardt** [comment]
Aaa finally I could test it! :) There’s options to also allow testing with HTTP:

- Firefox: https://developer.mozilla.org/en-US/docs/Web/API/Service_Worker_API/Using_Service_Workers#Developer_tools
- Chrome: https://stackoverflow.com/questions/34160509/options-for-testing-service-workers-via-http

And with that all seems fine! :) Good stuff @peeyushsingla

**Pull request merged**
